### PR TITLE
Hello Twcash ive made a list of turrets no need for spriting them in ive done that for you

### PR DESCRIPTION
**Pull request by Mr-Fisho**
Ive made a few turrets all of the have thier own folders

archer: small railgun turret
blaze: medium shrapnel blast cannon
synaps: sapping laser turret

but you have to code them and make the ui for them = )

### CODE REVIEW

**Comment by Twcash** [comment]
sprites will need work to fit with the style but interesting for sure. I will merge onto a separate branch and get to work then.

**Comment by Mr-Fisho** [comment]
Sure thing man Im kind of new to spriting so they dont have much good quality but i can cook up some wild ideas

**Comment by Mr-Fisho** [comment]
can i use the sprites as references

**Comment by Twcash** [comment]
Yes sure

**Comment by Mr-Fisho** [comment]
Hey btw where do u live so i can align our time zones

**Pull request merged**
