### PR TITLE
Wild life + laser earthquake turrets + new items and power genration

### PR DESCRIPTION
**Pull request by Mr-Fisho**
This adds 2 new turrets

1.the behemoth an earthquake turret
behemoth turret:
behemoth-preveiw
2.dendrite a beast of an electric laser
3.stinger a triple missle launcher (banshee but better)
and also adds two new units in the wildlife category
cepheloid and crustear both being kamikaze units they blow up on  contact with the player's blocks dealing mediocre damage
this is the cepheloid
cepheloid-full
this is the crustear
crustear-full

we also have a new abyssal biome the gloweed forests
and crude units 
units made by the crude assembler. crude units are made of walls and turrets they pack a punch but have low health
enemy
nemisis
rival

also adds new items
odinum
graphenite
chormium

new crafters
odinum enricher
ac alloy forge (know as au alloy forges in the files)
chromium forges are added too you can identify them by their white markings

adds new liquids
odinum refridgerant
ammonia

a new pump for getting ammonia
and an ammonia burner generates power from ammonia

Adds a new reactor the odinum reactor
 and a new t3 core unit the derive

### CODE REVIEW

**Comment by Mr-Fisho** [comment]
the turret ive shown u is the behemoth more content will come soon

**Comment by Mr-Fisho** [comment]
and a new biome is added too

**Comment by Mr-Fisho** [comment]
btw meassage me what will make the cut the things that not make it i will improve their concepts so they work better ; )

**Comment by Mr-Fisho** [comment]
Btw also tell me where you live

**Comment by Mr-Fisho** [comment]
hey are you online

**Comment by Mr-Fisho** [comment]
because when are u gonna add the stuff from my pull request

**Comment by Mr-Fisho** [comment]
If me no get answer soon ima add **MOAR** content

**Comment by Mr-Fisho** [comment]
*Angry fish noises*

**Comment by Mr-Fisho** [comment]
By the way ill make a different fork because this is getting a bit messy

**Comment by Twcash** [comment]
reopening when I have the time

**Comment by Mr-Fisho** [comment]
oh! of course i will help you de-clutter the mod i can help with that, By the way ive been making a new mod but i need help with coding it in it osore the scorched wastes i do have some sprites already

**Comment by Mr-Fisho** [comment]
Well what do you need help with to be spescific and by the way how to get hydrogen chloride for duramium and can i help resprite some things like walls and items to make them have the aquatic ding to them

**Comment by Twcash** [comment]
Mainly help with balancing and ratios

**Comment by Twcash** [comment]
Especially turrets

**Comment by Mr-Fisho** [comment]
and can i help making new sprites for the material im no good for coding but i am the sharpest tool for making sprites
and can i help you remake the sectors many of them will be ready this week and im coming up with a poster for the mod
and also you can see ive changed the way the sprites look of the turrets

**Comment by Mr-Fisho** [comment]
the turrets ive made before can be compared to what ive made now

**Comment by Mr-Fisho** [comment]
i can help by giving the turrets unique bullets and dmg when using differing ammo

**Comment by Mr-Fisho** [comment]
me no have discord ima fire it up soon and give me the link or something to ur discord

**Comment by Twcash** [comment]
Just on the mindus discord I have a forum

**Comment by Mr-Fisho** [comment]
where can i meet you in discord

**Comment by Twcash** [comment]
Aquarion in modding forums

**Comment by Mr-Fisho** [comment]
nice meet me in a minute

**Comment by Mr-Fisho** [comment]
im here but wait for 3 mins becaause its telling me to be a member for ten mins

**Pull request closed without merging**
