### PR TITLE
lmao its that ez to fix the crash

### PR DESCRIPTION
**Pull request by camelStyleUser**
use each or i will murder you

### CODE REVIEW

**Comment by camelStyleUser** [comment]
@Leo-MathGuy killer use each

**Comment by Leo-MathGuy** [comment]
dam im stupid havent used js in a year

**Comment by Leo-MathGuy** [comment]
@camelStyleUser uhm no its a seq not an array 🤓

**Comment by camelStyleUser** [comment]
> @camelStyleUser uhm no its a seq not an array 🤓

then convert it to a seq
skill issue

**Pull request merged**
