### PR TITLE
Rush translation (merge when done renaming everything)

### PR DESCRIPTION
**Pull request by Leo-MathGuy**

### CODE REVIEW

**Comment by Andromeda-Galaxy29** [comment]
Please change Редактировать back to Редактирование

Russian translations dont use verbs as names for things

**Comment by Twcash** [comment]
H will this work in 146?

**Comment by Twcash** [comment]
Also if you doing this put the types: back into the files

**Comment by Leo-MathGuy** [comment]
@Andromeda-Galaxy29 I was born in Russia, (English is my second language). I have the Russian language theory textbook, and yes, Russian language does use verbs (most commonly infinitives) as names.

Both Редактировать and Редактирование aren't accurate translations, as I can't recall an equivalent of "Censorship" as what I think "Redact" is supposed to mean (Like "Redacted content")

Moreover, I used my repo as a test for my PR, I was going to close this anyway

**Comment by Andromeda-Galaxy29** [comment]
@Leo-MathGuy I am also natively Russian. Im not telling you that it's impossible to name something with a verb in **russian**, I'm telling you that the **vanilla mindustry translation** doesn't do that. Example - Diffuse (a verb) is translated as Разброс (a noun)

**Comment by Leo-MathGuy** [comment]
Thats why I said not in this context

**Comment by Andromeda-Galaxy29** [comment]
oh ok

**Pull request closed without merging**
